# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170814_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='A coding Dojo in a place'),
            preserve_default=False,
        ),
    ]
